# Generated by Django 5.0.2 on 2024-06-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='familya',
            field=models.CharField(default='salom', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talaba',
            name='ism',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
    ]
